---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/base/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
