---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: isk-reloader
spec:
  interval: 1m
  chart:
    spec:
      chart: reloader
      version: v1.0.2
      sourceRef:
        kind: HelmRepository
        name: stakater-chart
        namespace: flux-system
  values:
    reloader:
      ignoreSecrets: false
      ignoreConfigMaps: false
      reloadStrategy: annotations # Set to default, env-vars or annotations
